const colors = {
  light: {
    text: "#13485A",
    tint: "#13485A",
    background: "#FFFFFF",
    foreground: "#13485A",
    card: "#FFFFFF",
    cardForeground: "#13485A",
    primary: "#13485A",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF0F5",
    secondaryForeground: "#13485A",
    muted: "#EEF0F5",
    mutedForeground: "#6E7E8D",
    accent: "#C91A1A",
    accentForeground: "#FFFFFF",
    destructive: "#C91A1A",
    destructiveForeground: "#FFFFFF",
    border: "#E2E5EC",
    input: "#E2E5EC",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#1B6B87",
    background: "#091E26",
    foreground: "#FFFFFF",
    card: "#0F2D3A",
    cardForeground: "#FFFFFF",
    primary: "#1B6B87",
    primaryForeground: "#FFFFFF",
    secondary: "#0F2D3A",
    secondaryForeground: "#FFFFFF",
    muted: "#0F2D3A",
    mutedForeground: "#8BAABC",
    accent: "#E53030",
    accentForeground: "#FFFFFF",
    destructive: "#E53030",
    destructiveForeground: "#FFFFFF",
    border: "#1A3D4D",
    input: "#1A3D4D",
  },
  radius: 10,
};

export default colors;
